# Generated by Django 2.0.4 on 2018-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=70)),
                ('available_room', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
