# Generated by Django 2.0.4 on 2018-04-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=70)),
                ('available_beds', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel')),
            ],
        ),
    ]
