# Generated by Django 2.0.4 on 2018-04-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
