# Generated by Django 2.0.4 on 2018-04-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20180409_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('mobile_no', models.IntegerField()),
                ('program_of_study', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('year_of_admission', models.DateField()),
                ('duration_of_program', models.CharField(max_length=20)),
                ('equivalent_degree_of_jnu', models.BooleanField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Dormitory')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Room')),
            ],
        ),
    ]
