# Generated by Django 2.0.4 on 2018-04-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.Dormitory'),
        ),
    ]
