# Generated by Django 2.0.4 on 2018-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_auto_20180409_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='equivalent_degree_of_jnu',
            new_name='equivalent_degree',
        ),
        migrations.AddField(
            model_name='student',
            name='previous_degree_of_jnu',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registration_no',
            field=models.CharField(default='10/00/jc/010', max_length=20),
            preserve_default=False,
        ),
    ]
