# Generated by Django 2.0.4 on 2018-04-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20180411_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='hostel',
        ),
    ]
