# Generated by Django 2.0.4 on 2018-04-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='hostel',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='priority_status',
            field=models.IntegerField(default=' '),
            preserve_default=False,
        ),
    ]
