# Generated by Django 2.0.4 on 2018-04-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_auto_20180421_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='hostel',
            field=models.OneToOneField(default='default', on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel'),
            preserve_default=False,
        ),
    ]
