# Generated by Django 2.0.4 on 2018-04-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_auto_20180421_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='hostel',
        ),
    ]
