# Generated by Django 2.0.4 on 2018-04-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_remove_dormitory_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='hostel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel'),
            preserve_default=False,
        ),
    ]
