# Generated by Django 2.0.4 on 2018-04-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_dormitory_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='priority_status',
        ),
    ]
