# Generated by Django 2.0.4 on 2018-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_student_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
